export enum UsageAction {
  RECIPE_GENERATION = 'RECIPE_GENERATION',
  RECIPE_PARSE = 'RECIPE_PARSE',
  RECIPE_SUGGEST = 'RECIPE_SUGGEST',
  MEAL_PLAN_SAVE = 'MEAL_PLAN_SAVE',
  PARSE_IMAGE = 'PARSE_IMAGE',
  SMART_GROUP = 'SMART_GROUP',
}
